title: "Sri Harsha Koppu"
name: "Sri Harsha Koppu"
description: "DevOps & Cloud Engineer | AWS | Kubernetes | CI/CD | Security"
url: "https://Harshacric945.github.io"
github_username: Harshacric945
linkedin_username: sriharshakoppu945
